LANGUAGES = {
    "English": {
        "loading": "Loading...",
        "app_title": "SecureVault Pro",
        "app_slogan": "~ ONLY YOU OPEN IT !",
        "initializing": "Initializing...",
        "starting_engine": "Starting up the engine...",
        "loading_components": "Loading components...",
        "verifying_security": "Verifying security...",
        "preparing_workspace": "Preparing workspace...",
        "launching_application": "Launching application...",
        "enter_master_password": "Enter Master Password",
        "login": "🔓 Login",
        "first_time_setup": "⚙️ First Time Setup",
        "error": "Error",
        "enter_master_password_error": "Please enter your master password",
        "vault_not_initialized_error": "Vault is not initialized. Please run first time setup.",
        "migration_error_title": "Migration Error",
        "migration_error_body": "Failed to migrate legacy files",
        "account_locked_error_title": "Account Locked",
        "secure_storage_init_error": "Failed to initialize secure storage",
        "secure_storage_load_error": "Failed to load files from secure storage.",
        "diagnostic_report": "🔍 Diagnostic Report:",
        "invalid_master_password_error": "Invalid master password. {attempts} attempts remaining.",
        "account_locked_error": "Too many failed attempts. Account locked for {minutes} minutes.",
        "integrity_error_title": "Integrity Error",
        "integrity_error_body": "Database integrity check failed. This usually happens when:\n\n"
                              "• Database files were modified outside the application\n"
                              "• The application was not properly closed\n"
                              "• There was a system crash\n\n"
                              "Would you like to attempt to fix this automatically?",
        "success": "Success",
        "integrity_fix_success": "Integrity issue fixed! Please try logging in again.",
        "integrity_fix_fail": "Failed to fix integrity issue automatically.",
        "integrity_fix_error": "Failed to fix integrity issue: {error}",
        "settings": "Settings",
        "about": "About",
        "logout": "Logout",
        "language_settings": "Language Settings",
        "language": "Language",
        "language_change_title": "Language Changed",
        "language_change_message": "Please restart the application for the changes to take full effect.",
        "navigation": "Navigation",
        "your_accounts": "Your Accounts",
        "password_generator": "Password Generator",
        "security_report": "Security Report",
        "check_update_online": "online update",
        "your_accounts_title": "🔑 Your Accounts",
        "add_new_account": "➕ Add New Account",
        "search_placeholder": "🔍 Search by name, email, or URL...",
        "no_accounts_found_search": "No accounts found matching your search.",
        "no_accounts_found": "📝 No accounts found",
        "no_username": "No username",
        "no_url": "No URL",
        "strength_template": "🛡️ {strength}",
        "unknown_strength": "Unknown",
        "view_action": "👁️ View",
        "copy_password_action": "📋 Copy Password",
        "open_action": "🌐 Open",
        "edit_action": "✏️ Edit Data",
        "delete_action": "🗑️ Delete Account",
        "password_generator_title": "🛠️ Password Generator",
        "generator_settings": "Generator Settings",
        "password_length": "Password Length:",
        "password_length_template": "{value} characters",
        "character_types": "Character Types:",
        "include_uppercase": "Include Uppercase (A-Z)",
        "include_lowercase": "Include Lowercase (a-z)",
        "include_digits": "Include Digits (0-9)",
        "include_symbols": "Include Symbols (!@#$...)",
        "exclude_ambiguous": "Exclude Ambiguous (0, O, 1, l, I)",
        "generate_password_action": "🎲 Generate Password",
        "generated_password": "Generated Password",
        "copy_action": "📋 Copy",
        "regenerate_action": "🔄 Regenerate",
        "strength_analysis_title": "Password Strength Analysis",
        "generate_to_see_analysis": "Generate a password to see analysis",
        "strength_analysis_template": "Strength: {strength} ({score}/100)\nLength: {length} characters\nUnique characters: {unique_chars}",
        "copied_title": "Copied",
        "copied_message": "Password copied to clipboard!",
        "no_password_to_copy": "No password to copy",
        "security_report_title": "🛡️ Security Report",
        "overall_statistics": "📊 Overall Statistics",
        "statistics_template": "Total Accounts: {total_accounts}\nStrong Passwords: {strong_passwords}\nWeak Passwords: {weak_passwords}\nDuplicate Passwords: {duplicate_passwords}",
        "weak_passwords_title": "⚠️ Accounts with Weak Passwords",
        "weak_password_template": "{name}: {strength} ({score}/100)",
        "duplicate_passwords_title": "🔄 Accounts with Duplicate Passwords",
        "shared_by_template": "Shared by: {names}",
        "report_error_template": "Error generating security report: {error}",
        "use_at_least_12_chars": "Use at least 12 characters",
        "add_lowercase": "Add lowercase letters",
        "add_uppercase": "Add uppercase letters",
        "add_numbers": "Add numbers",
        "add_symbols": "Add symbols",
        "avoid_repeated_chars": "Avoid repeated characters",
        "avoid_common_patterns": "Avoid common patterns",
        "app_title_with_icon": "SecureVault Pro",
        "verify_master_password_title": "Verify Master Password",
        "auth_required": "🔐 Authentication Required",
        "master_password_placeholder": "Master Password",
        "cancel_button": "Cancel",
        "ok_button": "OK",
        "invalid_master_password": "Invalid master password",
        "auth_failed": "Authentication failed",
        "setup_wizard_title": "SecureVault Pro Setup Wizard",
        "create_master_password_title": "Create Your Master Account",
        "email_placeholder": "Your E-mail Ex. example@gmail.com",
        "email_required_error": "Email is a required field",
        "confirm_password_placeholder": "Confirm Password",
        "complete_setup_button": "Complete Setup",
        "passwords_dont_match": "Passwords don't match or are empty",
        "password_too_short": "Password must be at least 16 characters long.",
        "setup_success_message": "SecureVault Pro has been set up successfully!",
        "setup_failed_message": "Setup failed: {error}",
        "password_strength_template": "Length: {length} chars | Strength: {strength} ({score}/100)",
        "main_toolbar_title": "SecureVault Pro",
        "delete_confirm_title": "Confirm Delete",
        "delete_confirm_message": "Are you sure you want to delete '{account_name}'?\\n\\nThis action cannot be undone!",
        "delete_success_title": "Deleted",
        "delete_success_message": "Account '{account_name}' has been deleted.",
        "update_confirm_title": "Confirm Update",
        "update_confirm_message": "Are you sure you want to update '{account_name}'?\n\nThe current data will be replaced with the new data you entered.",
        "delete_failed_message": "Failed to delete account: {error}",
        "account_details_title": "Account Details - {account_name}",
        "view_details_title": "🔍 {account_name}",
        "account_name_label": "Account Name:",
        "username_label": "Username:",
        "email_label": "Email:",
        "website_label": "Website:",
        "password_label": "Password:",
        "notes_label": "Notes:",
        "not_set": "Not set",
        "not_available": "Not available",
        "no_notes_available": "No notes available",
        "copy_password_button": "📋 Copy Password",
        "close_button_label": "Close",
        "copy_success_message": "Password for {account_name} copied to clipboard!",
        "password_not_found": "Password not found",
        "copy_failed_message": "Failed to copy password: {error}",
        "website_open_disabled_title": "Info",
        "website_open_disabled_message": "Website opening functionality has been disabled for security.",
        "edit_account_title": "Edit Account - {account_name}",
        "add_account_title": "Add New Account",
        "edit_account_icon_title": "✏️ Edit Account",
        "add_account_icon_title": "➕ Add New Account",
        "username_email_label": "Username / Email:",
        "website_url_label": "Website URL:",
        "update_account_button": "Update Account",
        "add_account_button": "Add Account",
        "expired_passwords_count": "Expired Passwords: {count}",
        "account_name_required": "Account name is required",
        "password_required": "Password is required",
        "update_success_message": "Account '{account_name}' updated successfully!",
        "id_generation_failed": "Failed to generate unique account ID. Please try again.",
        "duplicate_name_title": "Duplicate Name",
        "duplicate_name_message": "An account with the name '{account_name}' already exists.\\n\\nDo you want to create it anyway?",
        "add_success_message": "Account '{account_name}' added successfully!",
        "duplicate_account_error": "An account with this information already exists.\\n\\nError: {error}",
        "database_error": "Database error: {error}",
        "create_failed_message": "Failed to create account: {error}",
        "save_failed_message": "Failed to save account: {error}",
        "create_vault_files_error": "Failed to create secure vault files",
        "security_settings_title": "Security Settings",
        "master_password_label": "Master Password",
        "change_master_password_button": "Change Master Password",
        "auto_logout_title": "Automatic Logout",
        "auto_logout_message": "For your security, the application will automatically \n lock and close after 15 minutes of inactivity",
        "change_master_password_dialog_title": "Change Master Password",
        "change_master_password_icon_title": "🔒 Change Master Password",
        "current_password_label": "Current Password:",
        "current_password_placeholder": "Enter current password",
        "new_password_label": "New Password:",
        "new_password_placeholder": "Enter new password",
        "confirm_new_password_label": "Confirm New Password:",
        "confirm_new_password_placeholder": "Confirm new password",
        "changing_password_status": "🔄 Changing password...",
        "current_password_required_error": "❌ Current password is required",
        "new_password_required_error": "❌ New password is required",
        "new_password_min_length_error": "❌ New password must be at least 8 characters",
        "new_passwords_no_match_error": "❌ New passwords don't match",
        "new_password_must_be_different_error": "❌ New password must be different from current",
        "password_changed_success_status": "✅ Password changed successfully!",
        "password_changed_success_title": "Password Changed Successfully",
        "password_changed_success_message": "Master password changed successfully! \n\n🔄 The program will now restart to ensure all changes take effect. \n\nPlease wait while the application restarts...",
        "current_password_incorrect_error": "Current password is incorrect",
        "password_change_failed_error": "Password change failed: {error}",
        "password_change_failed_status": "❌ Password change failed",
        "about_dialog_title": "About SecureVault Pro",
        "about_slogan": "~ ONLY YOU OPEN IT !",
        "about_text": """SecureVault Pro is a robust, desktop-based application designed to securely store and manage your sensitive login credentials. Built with a focus on security and user privacy, it uses strong encryption algorithms to protect your data locally on your computer.

### How It Works

When you first set up SecureVault, you create a Master Password. This password, combined with a randomly generated salt, is used to create a powerful encryption key. This key is never stored directly. Instead, it is generated on-the-fly each time you log in.

All the account information you save is encrypted with this key before being written to the database files on your computer's disk. When you need to view or copy a password, the application decrypts it in memory just long enough for you to use it.

This design ensures that even if someone gains access to your computer's files, they cannot read your passwords without knowing your Master Password.

### Security Best Practices

*   **Use a Strong Master Password:** Make it long, complex, and something you have never used anywhere else.
---
_THIS SYSTEM WAS DEVELOPED BY HAMZA SAADI FROM _EAGLESHADOW 2025_
""",
        "close_button": "Close",
        "tutorial_title": "Tutorial",
        "tutorial_step_1_title": "Welcome to SecureVault Pro",
        "tutorial_step_1_text": """This short tutorial will walk you through the essential features of SecureVault Pro.

This application is your personal digital vault for storing passwords and other sensitive information. All your data is stored securely on your local computer, not in the cloud. Everything is encrypted using powerful, industry-standard algorithms.

Think of encryption as a secret code. Only your Master Password can unlock this code, ensuring that you, and only you, can access your private data.""",
        "tutorial_step_2_title": "Your Master Password is Your Only Key",
        "tutorial_step_2_text": """Your Master Password is the most critical piece of your security. It is the one and only key that can unlock your vault.

**IMPORTANT:** We do not store your Master Password anywhere. This means if you forget it, there is no way to recover your data. This is a security feature designed to protect you.

Please choose a strong, memorable password and keep it safe.""",
        "tutorial_step_3_title": "Feature Overview",
        "tutorial_step_3_text": """Here's a quick look at what you can do with SecureVault Pro:

• **Manage Accounts:** Securely add, edit, and delete your login credentials for websites and applications.
• **Password Generator:** Create strong, random, and customizable passwords to protect your accounts.
• **Security Report:** The app analyzes your passwords and alerts you to any that are weak or have been reused across multiple accounts.""",
        "tutorial_step_4_title": "Adding and Managing Your Accounts",
        "tutorial_step_4_text": """To get started, click the '➕ Add New Account' button on the main screen.

Fill in the details for your account, such as the account name, username, and website. When it comes to the password, you can either enter an existing one or use the built-in Password Generator to create a new, strong one.

You can view, edit, or delete your accounts at any time from the main list.""",
        "tutorial_step_5_title": "Tips for Staying Secure",
        "tutorial_step_5_text": """To get the most out of SecureVault Pro and keep your digital life secure, follow these best practices:

• **Use a Strong Master Password:** Make it long, complex, and unique.
• **Generate Strong Passwords:** Use the password generator for all your accounts. Avoid using simple or easily guessable passwords.""",
        "tutorial_step_6_title": "All Done!",
        "tutorial_step_6_text": "You're now ready to use SecureVault Pro to manage your passwords and enhance your online security.",
        "tutorial_step_7_title": "FINALLY, REMEMBER...",
        "tutorial_step_7_text": "Be SMART and STAY SAFE!",
        "tutorial_progress_text": "{current_step} of {total_steps}",
        "previous_button": "Previous",
        "next_button": "Next",
        "finish_button": "Finish",
        "skip_button": "Skip",
        "email_updated_success_message": "Your email has been updated successfully.",
        "email_update_failed_error": "Failed to update your email. Error: {error}",
        "invalid_email_format_error": "Invalid email format. Please enter a valid email address.",
        "two_factor_auth_title": "Two-Factor Authentication (2FA)",
        "two_factor_auth_enabled": "Two-Factor Authentication: Enabled",
        "two_factor_auth_disabled": "Two-Factor Authentication: Disabled",
        "two_factor_auth_description": "Add an extra layer of security to your account. When enabled, you'll need to enter a code from your authenticator app in addition to your master password.",
        "enable_2fa_button": "Enable Two-Factor Authentication",
        "disable_2fa_button": "Disable Two-Factor Authentication",
        "2fa_setup_title": "Setup Two-Factor Authentication",
        "2fa_setup_step1": "Step 1: Scan the QR code with your authenticator app",
        "2fa_setup_step2": "Step 2: Enter the 6-digit code from your app to verify",
        "2fa_setup_instructions": "1. Install an authenticator app on your phone (Google Authenticator, Microsoft Authenticator, Authy, etc.)\n2. Scan the QR code below with your app\n3. Enter the 6-digit code shown in your app to complete setup",
        "2fa_verification_code_label": "Enter 6-digit code:",
        "2fa_verification_code_placeholder": "000000",
        "2fa_verify_button": "Verify & Enable",
        "2fa_setup_success": "Two-Factor Authentication has been enabled successfully!",
        "2fa_setup_failed": "Failed to enable Two-Factor Authentication. Please try again.",
        "2fa_invalid_code": "Invalid code. Please check your authenticator app and try again.",
        "2fa_disable_confirm_title": "Disable Two-Factor Authentication",
        "2fa_disable_confirm_message": "Are you sure you want to disable Two-Factor Authentication? This will reduce the security of your account.",
        "2fa_disabled_success": "Two-Factor Authentication has been disabled.",
        "2fa_login_required": "Two-Factor Authentication Required",
        "2fa_login_code_label": "Enter the 6-digit code from your authenticator app:",
        "2fa_login_code_placeholder": "000000",
        "2fa_login_verify_button": "Verify",
        "2fa_login_invalid_code": "Invalid code. Please try again.",
        "2fa_login_locked_out": "Too many failed attempts. 2FA is locked for {minutes} minutes.",
        "2fa_library_missing": "2FA functionality requires pyotp and qrcode libraries. Install with: pip install pyotp qrcode[pil]",
        "2fa_not_configured": "Two-Factor Authentication is not configured.",
        "security_questions_title": "Security Questions",
        "security_questions_instruction": "Please select 3 out of 5 questions and provide answers.",
        "security_questions_error_title": "Security Questions Error",
        "security_questions_error_message": "Please select exactly 3 questions and provide answers for them.",
        "security_question_1": "What was your childhood nickname?",
        "security_question_2": "In what city did you meet your spouse/significant other?",
        "security_question_3": "What is the name of your favorite childhood friend?",
        "security_question_4": "What was the name of your first pet?",
        "security_question_5": "What was the name of the company where you had your first job?",
        "answer_placeholder": "Your answer here",
        "invalid_answer": "The answer is incorrect. Please try again.",
        "security_alert": "Security Alert",
        "suspicious_activity_detected": "Suspicious activity detected. The application will now close.",
        "app_locked_title": "Application Locked",
        "app_locked_message": "The application is locked due to suspicious activity. Please wait {time} before trying again.",
        "action_not_allowed_title": "Action Not Allowed",
        "action_not_allowed_body": "Closing the application is not allowed from this screen. Please log out first to ensure your data is saved securely.",
        "check_for_updates": "Check for Updates",
        "check_for_updates_title": "Check for Updates",
        "check_updates_now": "Check Updates Now",
        "update_check_info": "Click the button below to check for updates. This will connect to the internet.",
        "contact_developer": "Contact Developer",
        "checking_for_updates": "Checking for updates...",
        "no_updates_available": "You are on the latest version.",
        "update_available": "A new version is available!",
        "update_url_placeholder": "Or visit: https://example.com/updates",
        "activation": "Activation",
        "activation_prompt": "Please enter your license key:",
        "activation_success_title": "Activation Successful",
        "activation_success_message": "Thank you for your purchase, The application has been successfully activated. The program will automatically restart for the changes to take effect.",
        "activation_failed_title": "Activation Failed",
        "activation_failed_message": "The license key is incorrect. You have {attempts_left} attempts remaining.",
        "activation_locked_out_message": "Too many incorrect activation attempts. For your security, activation has been temporarily blocked for {lockout_time}.",
        "password_change_reminder_title": "Password Change Reminder",
        "password_change_reminder": "It's been 5 minutes since you created the account '{account_name}'.\n\nWould you like to change the password now?",
        "weak_password_recommendation": "(We do not recommend continuing to use this password)",
        "medium_password_warning": "(It could be vulnerable to hacking at any time)",
        "master_password_warning": "Please be aware: Your Master Password is the only key to your vault. If you forget it, your data cannot be recovered. We recommend storing it in a secure, offline location.",
        "password_req_length": "At least 16 characters",
        "password_req_uppercase": "An uppercase letter (A-Z)",
        "password_req_lowercase": "A lowercase letter (a-z)",
        "password_req_number": "A number (0-9)",
        "password_req_symbol": "A symbol (!@#$)",
        "password_requirements_not_met": "Please ensure your password meets all requirements.",
        "welcome_title": "Welcome to SecureVault Pro!",
        "welcome_message_1": "Your secure vault is ready. Let's get you started.",
        "welcome_feature_1_title": "🔐 Store Securely",
        "welcome_feature_1_desc": "Add your accounts, and we'll encrypt and store them securely on your device.",
        "welcome_feature_2_title": "🎲 Generate Passwords",
        "welcome_feature_2_desc": "Create strong, random passwords to protect your online accounts from unauthorized access.",
        "welcome_feature_3_title": "🛡️ Stay Safe",
        "welcome_feature_3_desc": "Use our security report to find and fix weak or reused passwords.",
        "get_started_button": "Let's Get Started",
        "duplicate_answers_error": "You cannot use the same answer for multiple security questions. Please provide unique answers for each question.",
        "invalid_email_domain_error": "Please use a valid email",
        "filter_show_all": "Show All",
        "filter_weak_passwords": "Weak Passwords",
        "filter_expired_passwords": "Expired Passwords",
        "filter_by_label": "Filter by:",
        "backup": "Backup",
        "restore": "Restore",
        "restore_confirm_title": "Confirm Restore",
        "restart_title": "Restart Required",
        "verify_button": "Verify",
        "trial_limit_title": "Trial Limit Reached",
        "trial_limit_message": "You have reached the 3-account limit for the trial version. Please activate the full version to add unlimited accounts."
    },
    "Arabic": {
        "loading": "جار التحميل...",
        "app_title": "SecureVault Pro",
        "app_slogan": "~ أنت فقط من يفتحه!",
        "initializing": "جار التهيئة...",
        "starting_engine": "جار تشغيل المحرك...",
        "loading_components": "جار تحميل المكونات...",
        "verifying_security": "جار التحقق من الأمان...",
        "preparing_workspace": "جار تحضير مساحة العمل...",
        "launching_application": "جار إطلاق التطبيق...",
        "enter_master_password": "أدخل كلمة المرور الرئيسية",
        "login": "🔓 تسجيل الدخول",
        "first_time_setup": "⚙️ الإعداد لأول مرة",
        "error": "خطأ",
        "enter_master_password_error": "الرجاء إدخال كلمة المرور الرئيسية الخاصة بك",
        "vault_not_initialized_error": "الخزنة غير مهيأة. الرجاء تشغيل الإعداد لأول مرة.",
        "migration_error_title": "خطأ في الترحيل",
        "migration_error_body": "فشل ترحيل الملفات القديمة",
        "account_locked_error_title": "تم قفل الحساب",
        "secure_storage_init_error": "فشل تهيئة التخزين الآمن",
        "secure_storage_load_error": "فشل تحميل الملفات من التخزين الآمن.",
        "diagnostic_report": "🔍 تقرير التشخيص:",
        "invalid_master_password_error": "كلمة المرور الرئيسية غير صالحة. تبقى لديك {attempts} محاولات.",
        "account_locked_error": "محاولات فاشلة كثيرة جدًا. تم قفل الحساب لمدة {minutes} دقائق.",
        "integrity_error_title": "خطأ في التكامل",
        "integrity_error_body": "فشل التحقق من تكامل قاعدة البيانات. يحدث هذا عادةً عندما:\n\n"
                              "• تم تعديل ملفات قاعدة البيانات خارج التطبيق\n"
                              "• لم يتم إغلاق التطبيق بشكل صحيح\n"
                              "• حدث عطل في النظام\n\n"
                              "هل ترغب في محاولة إصلاح هذا تلقائيًا؟",
        "success": "نجاح",
        "integrity_fix_success": "تم إصلاح مشكلة التكامل! الرجاء محاولة تسجيل الدخول مرة أخرى.",
        "integrity_fix_fail": "فشل إصلاح مشكلة التكامل تلقائيًا.",
        "integrity_fix_error": "فشل إصلاح مشكلة التكامل: {error}",
        "settings": "الإعدادات",
        "about": "حول",
        "logout": "تسجيل الخروج",
        "language_settings": "إعدادات اللغة",
        "language": "اللغة",
        "language_change_title": "تم تغيير اللغة",
        "language_change_message": "الرجاء إعادة تشغيل التطبيق لتصبح التغييرات نافذة المفعول بالكامل.",
        "navigation": "التنقل",
        "your_accounts": "حساباتك",
        "password_generator": "مولد كلمات المرور",
        "security_report": "تقرير الأمان",
        "check_update_online": "تحديث عبر الإنترنت",
        "your_accounts_title": "🔑 حساباتك",
        "add_new_account": "➕ إضافة حساب جديد",
        "search_placeholder": "🔍 ابحث بالاسم أو البريد الإلكتروني أو الرابط...",
        "no_accounts_found_search": "لم يتم العثور على حسابات تطابق بحثك.",
        "no_accounts_found": "📝 لم يتم العثور على حسابات",
        "no_username": "لا يوجد اسم مستخدم",
        "no_url": "لا يوجد رابط",
        "strength_template": "🛡️ {strength}",
        "unknown_strength": "غير معروف",
        "view_action": "👁️ عرض",
        "copy_password_action": "📋 نسخ كلمة المرور",
        "open_action": "🌐 فتح",
        "edit_action": "✏️ تعديل البيانات",
        "delete_action": "🗑️ حذف الحساب",
        "password_generator_title": "🛠️ مولد كلمات المرور",
        "generator_settings": "إعدادات المولد",
        "password_length": "طول كلمة المرور:",
        "password_length_template": "{value} حرفًا",
        "character_types": "أنواع الأحرف:",
        "include_uppercase": "تضمين أحرف كبيرة (A-Z)",
        "include_lowercase": "تضمين أحرف صغيرة (a-z)",
        "include_digits": "تضمين أرقام (0-9)",
        "include_symbols": "تضمين رموز (!@#$...)",
        "exclude_ambiguous": "استبعاد الأحرف الغامضة (0, O, 1, l, I)",
        "generate_password_action": "🎲 توليد كلمة مرور",
        "generated_password": "كلمة المرور المولدة",
        "copy_action": "📋 نسخ",
        "regenerate_action": "🔄 إعادة التوليد",
        "strength_analysis_title": "تحليل قوة كلمة المرور",
        "generate_to_see_analysis": "قم بتوليد كلمة مرور لرؤية التحليل",
        "strength_analysis_template": "القوة: {strength} ({score}/100)\nالطول: {length} حرفًا\nالأحرف الفريدة: {unique_chars}",
        "copied_title": "تم النسخ",
        "copied_message": "تم نسخ كلمة المرور إلى الحافظة!",
        "no_password_to_copy": "لا توجد كلمة مرور لنسخها",
        "security_report_title": "🛡️ تقرير الأمان",
        "overall_statistics": "📊 الإحصائيات العامة",
        "statistics_template": "إجمالي الحسابات: {total_accounts}\nكلمات مرور قوية: {strong_passwords}\nكلمات مرور ضعيفة: {weak_passwords}\nكلمات مرور مكررة: {duplicate_passwords}",
        "weak_passwords_title": "⚠️ حسابات بكلمات مرور ضعيفة",
        "weak_password_template": "{name}: {strength} ({score}/100)",
        "duplicate_passwords_title": "🔄 حسابات بكلمات مرور مكررة",
        "shared_by_template": "مشتركة بواسطة: {names}",
        "report_error_template": "خطأ في توليد تقرير الأمان: {error}",
        "use_at_least_12_chars": "استخدم 12 حرفًا على الأقل",
        "add_lowercase": "أضف أحرفًا صغيرة",
        "add_uppercase": "أضف أحرفًا كبيرة",
        "add_numbers": "أضف أرقامًا",
        "add_symbols": "أضف رموزًا",
        "avoid_repeated_chars": "تجنب الأحرف المكررة",
        "avoid_common_patterns": "تجنب الأنماط الشائعة",
        "app_title_with_icon": "SecureVault Pro",
        "verify_master_password_title": "التحقق من كلمة المرور الرئيسية",
        "auth_required": "🔐 المصادقة مطلوبة",
        "master_password_placeholder": "كلمة المرور الرئيسية",
        "cancel_button": "إلغاء",
        "ok_button": "موافق",
        "invalid_master_password": "كلمة المرور الرئيسية غير صالحة",
        "auth_failed": "فشلت المصادقة",
        "setup_wizard_title": "معالج إعداد SecureVault Pro",
        "create_master_password_title": "أنشئ حسابك الرئيسي",
        "email_placeholder": "بريدك الإلكتروني، على سبيل المثال example@gmail.com",
        "email_required_error": "البريد الإلكتروني حقل مطلوب",
        "confirm_password_placeholder": "تأكيد كلمة المرور",
        "complete_setup_button": "إكمال الإعداد",
        "passwords_dont_match": "كلمتا المرور غير متطابقتين أو فارغتين",
        "password_too_short": "يجب أن تتكون كلمة المرور من 16 حرفًا على الأقل.",
        "setup_success_message": "تم إعداد SecureVault Pro بنجاح!",
        "setup_failed_message": "فشل الإعداد: {error}",
        "password_strength_template": "الطول: {length} حرفًا | القوة: {strength} ({score}/100)",
        "main_toolbar_title": "SecureVault Pro",
        "delete_confirm_title": "تأكيد الحذف",
        "delete_confirm_message": "هل أنت متأكد من أنك تريد حذف '{account_name}'؟\n\nلا يمكن التراجع عن هذا الإجراء!",
        "delete_success_title": "تم الحذف",
        "delete_success_message": "تم حذف الحساب '{account_name}'.",
        "update_confirm_title": "تأكيد التحديث",
        "update_confirm_message": "هل أنت متأكد من أنك تريد تحديث '{account_name}'؟\n\nسيتم استبدال البيانات الحالية بالبيانات الجديدة التي أدخلتها.",
        "delete_failed_message": "فشل حذف الحساب: {error}",
        "account_details_title": "تفاصيل الحساب - {account_name}",
        "view_details_title": "🔍 {account_name}",
        "account_name_label": "اسم الحساب:",
        "username_label": "اسم المستخدم:",
        "email_label": "البريد الإلكتروني:",
        "website_label": "الموقع الإلكتروني:",
        "password_label": "كلمة المرور:",
        "notes_label": "ملاحظات:",
        "not_set": "لم يتم التعيين",
        "not_available": "غير متوفر",
        "no_notes_available": "لا توجد ملاحظات متاحة",
        "copy_password_button": "📋 نسخ كلمة المرور",
        "close_button_label": "إغلاق",
        "copy_success_message": "تم نسخ كلمة المرور الخاصة بـ {account_name} إلى الحافظة!",
        "password_not_found": "لم يتم العثور على كلمة المرور",
        "copy_failed_message": "فشل نسخ كلمة المرور: {error}",
        "website_open_disabled_title": "معلومات",
        "website_open_disabled_message": "تم تعطيل وظيفة فتح الموقع الإلكتروني لأسباب أمنية.",
        "edit_account_title": "تعديل الحساب - {account_name}",
        "add_account_title": "إضافة حساب جديد",
        "edit_account_icon_title": "✏️ تعديل الحساب",
        "add_account_icon_title": "➕ إضافة حساب جديد",
        "username_email_label": "اسم المستخدم / البريد الإلكتروني:",
        "website_url_label": "رابط الموقع الإلكتروني:",
        "update_account_button": "تحديث الحساب",
        "add_account_button": "إضافة حساب",
        "expired_passwords_count": "كلمات المرور منتهية الصلاحية: {count}",
        "account_name_required": "اسم الحساب مطلوب",
        "password_required": "كلمة المرور مطلوبة",
        "update_success_message": "تم تحديث الحساب '{account_name}' بنجاح!",
        "id_generation_failed": "فشل إنشاء معرف حساب فريد. الرجاء المحاولة مرة أخرى.",
        "duplicate_name_title": "اسم مكرر",
        "duplicate_name_message": "يوجد حساب باسم '{account_name}' بالفعل.\n\nهل تريد إنشاؤه على أي حال؟",
        "add_success_message": "تمت إضافة الحساب '{account_name}' بنجاح!",
        "duplicate_account_error": "يوجد حساب بهذه المعلومات بالفعل.\n\nخطأ: {error}",
        "database_error": "خطأ في قاعدة البيانات: {error}",
        "create_failed_message": "فشل إنشاء الحساب: {error}",
        "save_failed_message": "فشل حفظ الحساب: {error}",
        "create_vault_files_error": "فشل إنشاء ملفات الخزنة الآمنة",
        "security_settings_title": "إعدادات الأمان",
        "master_password_label": "كلمة المرور الرئيسية",
        "change_master_password_button": "تغيير كلمة المرور الرئيسية",
        "auto_logout_title": "تسجيل الخروج التلقائي",
        "auto_logout_message": "لأمانك، سيتم قفل التطبيق وإغلاقه تلقائيًا\n بعد 15 دقيقة من عدم النشاط",
        "change_master_password_dialog_title": "تغيير كلمة المرور الرئيسية",
        "change_master_password_icon_title": "🔒 تغيير كلمة المرور الرئيسية",
        "current_password_label": "كلمة المرور الحالية:",
        "current_password_placeholder": "أدخل كلمة المرور الحالية",
        "new_password_label": "كلمة المرور الجديدة:",
        "new_password_placeholder": "أدخل كلمة المرور الجديدة",
        "confirm_new_password_label": "تأكيد كلمة المرور الجديدة:",
        "confirm_new_password_placeholder": "تأكيد كلمة المرور الجديدة",
        "changing_password_status": "🔄 جار تغيير كلمة المرور...",
        "current_password_required_error": "❌ كلمة المرور الحالية مطلوبة",
        "new_password_required_error": "❌ كلمة المرور الجديدة مطلوبة",
        "new_password_min_length_error": "❌ يجب أن تتكون كلمة المرور الجديدة من 8 أحرف على الأقل",
        "new_passwords_no_match_error": "❌ كلمتا المرور الجديدتان غير متطابقتين",
        "new_password_must_be_different_error": "❌ يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية",
        "password_changed_success_status": "✅ تم تغيير كلمة المرور بنجاح!",
        "password_changed_success_title": "تم تغيير كلمة المرور بنجاح",
        "password_changed_success_message": "تم تغيير كلمة المرور الرئيسية بنجاح! \n\n🔄 سيتم الآن إعادة تشغيل البرنامج لضمان تطبيق جميع التغييرات. \n\nالرجاء الانتظار أثناء إعادة تشغيل التطبيق...",
        "current_password_incorrect_error": "كلمة المرور الحالية غير صحيحة",
        "password_change_failed_error": "فشل تغيير كلمة المرور: {error}",
        "password_change_failed_status": "❌ فشل تغيير كلمة المرور",
        "about_dialog_title": "حول SecureVault Pro",
        "about_slogan": "~ أنت فقط من يفتحه!",
        "about_text": """SecureVault Pro هو تطبيق سطح مكتب قوي مصمم لتخزين وإدارة بيانات تسجيل الدخول الحساسة الخاصة بك بشكل آمن. تم تصميمه مع التركيز على الأمان وخصوصية المستخدم، ويستخدم خوارزميات تشفير قوية لحماية بياناتك محليًا على جهاز الكمبيوتر الخاص بك.

### كيف يعمل

عند إعداد SecureVault لأول مرة، تقوم بإنشاء كلمة مرور رئيسية. تُستخدم كلمة المرور هذه، بالإضافة إلى ملح تم إنشاؤه عشوائيًا، لإنشاء مفتاح تشفير قوي. لا يتم تخزين هذا المفتاح مباشرةً أبدًا. بدلاً من ذلك، يتم إنشاؤه بسرعة في كل مرة تقوم فيها بتسجيل الدخول.

يتم تشفير جميع معلومات الحساب التي تحفظها باستخدام هذا المفتاح قبل كتابتها في ملفات قاعدة البيانات على قرص الكمبيوتر الخاص بك. عندما تحتاج إلى عرض أو نسخ كلمة مرور، يقوم التطبيق بفك تشفيرها في الذاكرة لفترة كافية لاستخدامها.

يضمن هذا التصميم أنه حتى إذا تمكن شخص ما من الوصول إلى ملفات الكمبيوتر الخاص بك، فلن يتمكن من قراءة كلمات المرور الخاصة بك دون معرفة كلمة المرور الرئيسية الخاصة بك.

### أفضل ممارسات الأمان

*   **استخدم كلمة مرور رئيسية قوية:** اجعلها طويلة ومعقدة وشيء لم تستخدمه في أي مكان آخر.
---
_تم تطوير هذا النظام بواسطة حمزة السعدي من _EAGLESHADOW 2025_
""",
        "close_button": "إغلاق",
        "tutorial_title": "برنامج تعليمي",
        "tutorial_step_1_title": "مرحبًا بك في SecureVault Pro",
        "tutorial_step_1_text": """سيرشدك هذا البرنامج التعليمي القصير عبر الميزات الأساسية لـ SecureVault Pro.

هذا التطبيق هو خزنتك الرقمية الشخصية لتخزين كلمات المرور وغيرها من المعلومات الحساسة. يتم تخزين جميع بياناتك بشكل آمن على جهاز الكمبيوتر المحلي الخاص بك، وليس في السحابة. يتم تشفير كل شيء باستخدام خوارزميات قوية ومتوافقة مع معايير الصناعة.

فكر في التشفير كرمز سري. يمكن فقط لكلمة المرور الرئيسية الخاصة بك فك هذا الرمز، مما يضمن أنك، وأنت فقط، يمكنك الوصول إلى بياناتك الخاصة.""",
        "tutorial_step_2_title": "كلمة المرور الرئيسية الخاصة بك هي مفتاحك الوحيد",
        "tutorial_step_2_text": """كلمة المرور الرئيسية الخاصة بك هي الجزء الأكثر أهمية في أمانك. إنها المفتاح الوحيد الذي يمكنه فتح خزنتك.

**هام:** نحن لا نخزن كلمة المرور الرئيسية الخاصة بك في أي مكان. هذا يعني أنه إذا نسيتها، فلا توجد طريقة لاستعادة بياناتك. هذه ميزة أمنية مصممة لحمايتك.

الرجاء اختيار كلمة مرور قوية لا تنسى والاحتفاظ بها في مكان آمن.""",
        "tutorial_step_3_title": "نظرة عامة على الميزات",
        "tutorial_step_3_text": """إليك نظرة سريعة على ما يمكنك القيام به باستخدام SecureVault Pro:

• **إدارة الحسابات:** إضافة وتعديل وحذف بيانات تسجيل الدخول الخاصة بك للمواقع والتطبيقات بشكل آمن.
• **مولد كلمات المرور:** إنشاء كلمات مرور قوية وعشوائية وقابلة للتخصيص لحماية حساباتك.
• **تقرير الأمان:** يقوم التطبيق بتحليل كلمات المرور الخاصة بك وينبهك إلى أي كلمات مرور ضعيفة أو تم إعادة استخدامها عبر حسابات متعددة.""",
        "tutorial_step_4_title": "إضافة وإدارة حساباتك",
        "tutorial_step_4_text": """للبدء، انقر فوق الزر "➕ إضافة حساب جديد" على الشاشة الرئيسية.

املأ تفاصيل حسابك، مثل اسم الحساب واسم المستخدم والموقع الإلكتروني. عندما يتعلق الأمر بكلمة المرور، يمكنك إما إدخال كلمة مرور موجودة أو استخدام مولد كلمات المرور المدمج لإنشاء كلمة مرور جديدة وقوية.

يمكنك عرض أو تعديل أو حذف حساباتك في أي وقت من القائمة الرئيسية.""",
        "tutorial_step_5_title": "نصائح للحفاظ على الأمان",
        "tutorial_step_5_text": """لتحقيق أقصى استفادة من SecureVault Pro والحفاظ على أمان حياتك الرقمية، اتبع أفضل الممارسات التالية:

• **استخدم كلمة مرور رئيسية قوية:** اجعلها طويلة ومعقدة وفريدة من نوعها.
• **إنشاء كلمات مرور قوية:** استخدم مولد كلمات المرور لجميع حساباتك. تجنب استخدام كلمات مرور بسيطة أو سهلة التخمين.""",
        "tutorial_step_6_title": "انتهى كل شيء!",
        "tutorial_step_6_text": "أنت الآن جاهز لاستخدام SecureVault Pro لإدارة كلمات المرور الخاصة بك وتعزيز أمانك عبر الإنترنت.",
        "tutorial_step_7_title": "أخيرًا، تذكر...",
        "tutorial_step_7_text": "كن ذكيًا وحافظ على أمانك!",
        "tutorial_progress_text": "{current_step} من {total_steps}",
        "previous_button": "السابق",
        "next_button": "التالي",
        "finish_button": "إنهاء",
        "skip_button": "تخطي",
        "email_updated_success_message": "تم تحديث بريدك الإلكتروني بنجاح.",
        "email_update_failed_error": "فشل تحديث بريدك الإلكتروني. خطأ: {error}",
        "invalid_email_format_error": "تنسيق البريد الإلكتروني غير صالح. الرجاء إدخال عنوان بريد إلكتروني صالح.",
        "two_factor_auth_title": "المصادقة الثنائية (2FA)",
        "two_factor_auth_enabled": "المصادقة الثنائية: ممكّنة",
        "two_factor_auth_disabled": "المصادقة الثنائية: معطّلة",
        "two_factor_auth_description": "أضف طبقة إضافية من الأمان إلى حسابك. عند التمكين، ستحتاج إلى إدخال رمز من تطبيق المصادقة الخاص بك بالإضافة إلى كلمة المرور الرئيسية.",
        "enable_2fa_button": "تمكين المصادقة الثنائية",
        "disable_2fa_button": "تعطيل المصادقة الثنائية",
        "2fa_setup_title": "إعداد المصادقة الثنائية",
        "2fa_setup_step1": "الخطوة 1: امسح رمز الاستجابة السريعة باستخدام تطبيق المصادقة الخاص بك",
        "2fa_setup_step2": "الخطوة 2: أدخل الرمز المكون من 6 أرقام من تطبيقك للتحقق",
        "2fa_setup_instructions": "1. قم بتثبيت تطبيق مصادقة على هاتفك (Google Authenticator، Microsoft Authenticator، Authy، إلخ.)\n2. امسح رمز الاستجابة السريعة أدناه باستخدام تطبيقك\n3. أدخل الرمز المكون من 6 أرقام الموضح في تطبيقك لإكمال الإعداد",
        "2fa_verification_code_label": "أدخل الرمز المكون من 6 أرقام:",
        "2fa_verification_code_placeholder": "000000",
        "2fa_verify_button": "تحقق وتمكين",
        "2fa_setup_success": "تم تمكين المصادقة الثنائية بنجاح!",
        "2fa_setup_failed": "فشل تمكين المصادقة الثنائية. الرجاء المحاولة مرة أخرى.",
        "2fa_invalid_code": "رمز غير صالح. الرجاء التحقق من تطبيق المصادقة الخاص بك والمحاولة مرة أخرى.",
        "2fa_disable_confirm_title": "تعطيل المصادقة الثنائية",
        "2fa_disable_confirm_message": "هل أنت متأكد من أنك تريد تعطيل المصادقة الثنائية؟ سيؤدي هذا إلى تقليل أمان حسابك.",
        "2fa_disabled_success": "تم تعطيل المصادقة الثنائية.",
        "2fa_login_required": "المصادقة الثنائية مطلوبة",
        "2fa_login_code_label": "أدخل الرمز المكون من 6 أرقام من تطبيق المصادقة الخاص بك:",
        "2fa_login_code_placeholder": "000000",
        "2fa_login_verify_button": "تحقق",
        "2fa_login_invalid_code": "رمز غير صالح. الرجاء المحاولة مرة أخرى.",
        "2fa_login_locked_out": "محاولات فاشلة كثيرة جدًا. تم قفل المصادقة الثنائية لمدة {minutes} دقائق.",
        "2fa_library_missing": "تتطلب وظيفة المصادقة الثنائية مكتبتي pyotp و qrcode. قم بتثبيتهما باستخدام: pip install pyotp qrcode[pil]",
        "2fa_not_configured": "لم يتم تكوين المصادقة الثنائية.",
        "security_questions_title": "أسئلة الأمان",
        "security_questions_instruction": "الرجاء تحديد 3 أسئلة من أصل 5 وتقديم إجابات.",
        "security_questions_error_title": "خطأ في أسئلة الأمان",
        "security_questions_error_message": "الرجاء تحديد 3 أسئلة بالضبط وتقديم إجابات لها.",
        "security_question_1": "ما هو لقب طفولتك؟",
        "security_question_2": "في أي مدينة التقيت بزوجتك/شريكك؟",
        "security_question_3": "ما هو اسم صديق طفولتك المفضل؟",
        "security_question_4": "ما هو اسم حيوانك الأليف الأول؟",
        "security_question_5": "ما هو اسم الشركة التي عملت بها لأول مرة؟",
        "answer_placeholder": "إجابتك هنا",
        "invalid_answer": "الإجابة غير صحيحة. الرجاء المحاولة مرة أخرى.",
        "security_alert": "تنبيه أمني",
        "suspicious_activity_detected": "تم اكتشاف نشاط مشبوه. سيتم إغلاق التطبيق الآن.",
        "app_locked_title": "تم قفل التطبيق",
        "app_locked_message": "تم قفل التطبيق بسبب نشاط مشبوه. الرجاء الانتظار {time} قبل المحاولة مرة أخرى.",
        "action_not_allowed_title": "الإجراء غير مسموح به",
        "action_not_allowed_body": "إغلاق التطبيق غير مسموح به من هذه الشاشة. الرجاء تسجيل الخروج أولاً لضمان حفظ بياناتك بشكل آمن.",
        "check_for_updates": "التحقق من وجود تحديثات",
        "check_for_updates_title": "التحقق من وجود تحديثات",
        "check_updates_now": "التحقق من التحديثات الآن",
        "update_check_info": "انقر فوق الزر أدناه للتحقق من وجود تحديثات. سيتصل هذا بالإنترنت.",
        "contact_developer": "اتصل بالمطور",
        "checking_for_updates": "جار التحقق من وجود تحديثات...",
        "no_updates_available": "أنت تستخدم أحدث إصدار.",
        "update_available": "يتوفر إصدار جديد!",
        "update_url_placeholder": "أو قم بزيارة: https://example.com/updates",
        "activation": "تنشيط",
        "activation_prompt": "الرجاء إدخال مفتاح الترخيص الخاص بك:",
        "activation_success_title": "تم التنشيط بنجاح",
        "activation_success_message": "شكرًا لك على شرائك، تم تنشيط التطبيق بنجاح. سيتم إعادة تشغيل البرنامج تلقائيًا لتصبح التغييرات نافذة المفعول.",
        "activation_failed_title": "فشل التنشيط",
        "activation_failed_message": "مفتاح الترخيص غير صحيح. تبقى لديك {attempts_left} محاولات.",
        "activation_locked_out_message": "محاولات تنشيط غير صحيحة كثيرة جدًا. لأمانك، تم حظر التنشيط مؤقتًا لمدة {lockout_time}.",
        "password_change_reminder_title": "تذكير بتغيير كلمة المرور",
        "password_change_reminder": "لقد مرت 5 دقائق منذ إنشاء الحساب '{account_name}'.\n\nهل ترغب في تغيير كلمة المرور الآن؟",
        "weak_password_recommendation": "(لا نوصي بالاستمرار في استخدام كلمة المرور هذه)",
        "medium_password_warning": "(قد تكون عرضة للاختراق في أي وقت)",
        "master_password_warning": "الرجاء الانتباه: كلمة المرور الرئيسية الخاصة بك هي المفتاح الوحيد لخزنتك. إذا نسيتها، لا يمكن استعادة بياناتك. نوصي بتخزينها في مكان آمن وغير متصل بالإنترنت.",
        "password_req_length": "16 حرفًا على الأقل",
        "password_req_uppercase": "حرف كبير (A-Z)",
        "password_req_lowercase": "حرف صغير (a-z)",
        "password_req_number": "رقم (0-9)",
        "password_req_symbol": "رمز (!@#$)",
        "password_requirements_not_met": "الرجاء التأكد من أن كلمة المرور الخاصة بك تفي بجميع المتطلبات.",
        "welcome_title": "مرحبًا بك في SecureVault Pro!",
        "welcome_message_1": "خزنتك الآمنة جاهزة. لنبدأ.",
        "welcome_feature_1_title": "🔐 تخزين آمن",
        "welcome_feature_1_desc": "أضف حساباتك، وسنقوم بتشفيرها وتخزينها بشكل آمن على جهازك.",
        "welcome_feature_2_title": "🎲 توليد كلمات مرور",
        "welcome_feature_2_desc": "أنشئ كلمات مرور قوية وعشوائية لحماية حساباتك عبر الإنترنت من الوصول غير المصرح به.",
        "welcome_feature_3_title": "🛡️ حافظ على أمانك",
        "welcome_feature_3_desc": "استخدم تقرير الأمان الخاص بنا للعثور على كلمات المرور الضعيفة أو المعاد استخدامها وإصلاحها.",
        "get_started_button": "لنبدأ",
        "duplicate_answers_error": "لا يمكنك استخدام نفس الإجابة لأسئلة أمان متعددة. الرجاء تقديم إجابات فريدة لكل سؤال.",
        "invalid_email_domain_error": "الرجاء استخدام بريد إلكتروني صالح",
        "filter_show_all": "عرض الكل",
        "filter_weak_passwords": "كلمات مرور ضعيفة",
        "filter_expired_passwords": "كلمات مرور منتهية الصلاحية",
        "filter_by_label": "تصفية حسب:",
        "backup": "نسخ احتياطي",
        "restore": "استعادة",
        "restore_confirm_title": "تأكيد الاستعادة",
        "restart_title": "إعادة التشغيل مطلوبة",
        "verify_button": "تحقق",
        "trial_limit_title": "تم الوصول إلى حد الإصدار التجريبي",
        "trial_limit_message": "لقد وصلت إلى حد 20 حساب للإصدار التجريبي. الرجاء تنشيط الإصدار الكامل لإضافة عدد غير محدود من الحسابات."
    }
}


class LanguageManager:
    def __init__(self, language="English"):
        self.language = language
        self.supported_languages = list(LANGUAGES.keys())

    def set_language(self, language):
        if language in LANGUAGES:
            self.language = language
        else:
            self.language = "English"

    def get_string(self, key, **kwargs):
        string = LANGUAGES.get(self.language, {}).get(key, f"<{key}>")
        if kwargs:
            string = string.format(**kwargs)
        return string
