import os
import sys
import argparse
import platform

# It is safe to import these as this script is not part of the main application
# and is only intended for development/testing.
from guardian_anchor import GuardianAnchor
from guardian_observer import GuardianObserver
from trial_manager import TrialManager

# THIS IS A SECRET PASSWORD. A real application might use a more secure method
# for developer authentication, but for this context, a hardcoded secret is sufficient.
DEV_PASSWORD = "a_very_secret_dev_password_for_testing_only"

def find_and_delete_files(prefixes_and_dirs):
    """
    Scans directories for files with specific prefixes and deletes them.
    """
    deleted_count = 0
    failed_count = 0
    
    for name, data in prefixes_and_dirs.items():
        prefix = data["prefix"]
        directory = data["dir"]
        
        if not os.path.isdir(directory):
            print(f"[INFO] Directory for {name} not found: {directory}. Skipping.")
            continue

        found_files = False
        for filename in os.listdir(directory):
            if filename.startswith(prefix):
                found_files = True
                path_to_delete = os.path.join(directory, filename)
                try:
                    os.remove(path_to_delete)
                    print(f"[SUCCESS] Deleted {name}: {path_to_delete}")
                    deleted_count += 1
                except OSError as e:
                    print(f"[ERROR] FAILED to delete {name}: {path_to_delete}")
                    print(f"         Reason: {e}")
                    print(f"         RECOMMENDATION: Manually delete the file above and re-run this script with elevated (admin/sudo) privileges.")
                    failed_count += 1
        
        if not found_files:
            print(f"[INFO] No files with prefix '{prefix}' found in {directory}.")
            
    return deleted_count, failed_count


def clean_all_artifacts():
    """
    Finds and deletes all known artifacts from the new guardian-based trial system
    by scanning for discoverable filename prefixes.
    """
    print("--- Developer Cleanup Tool ---")
    print("Scanning for all trial-related artifacts...")

    try:
        # Instantiate guardians to get their file paths, which contain the base directories.
        anchor = GuardianAnchor()
        observer = GuardianObserver(anchor)
        # We need a dummy TrialManager just to get the license path.
        trial_manager = TrialManager(parent_window=None, restart_callback=None)

        # Define the prefixes and the base directories to scan.
        # We get the directory from the full path generated by the classes.
        search_locations = {
            "Anchor File(s)": {
                "prefix": "sv-anchor-",
                "dir": os.path.dirname(anchor.anchor_path)
            },
            "Observer File(s)": {
                "prefix": "sv-observer-",
                "dir": os.path.dirname(observer.observer_path)
            },
            "License File(s)": {
                "prefix": "sv-license-" if platform.system() == "Windows" else ".sv-license-",
                "dir": os.path.dirname(trial_manager.LICENSE_FILE)
            }
        }
        
        deleted, failed = find_and_delete_files(search_locations)

        print("\n--- Cleanup Summary ---")
        if failed > 0:
            print(f"🔴 FAILED to delete {failed} artifact(s). Please review the errors above and take manual action.")
        else:
            print(f"🟢 Successfully deleted {deleted} artifact(s).")
        print("The system should now be in a clean state.")

    except Exception as e:
        print(f"\nAn unexpected error occurred during cleanup: {e}")
        print("Please ensure all application modules are available and paths are correct.")

def main():
    """
    Main function to run the cleanup script.
    Parses command-line arguments to verify the developer password.
    """
    parser = argparse.ArgumentParser(
        description="""
        *** SecureVault Pro Developer Cleanup Tool ***
        This script completely removes all trial-related data, including hidden guardian files.
        It is for development and testing purposes ONLY.
        WARNING: This provides a clean slate and will reset the trial period entirely.
        """,
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    parser.add_argument(
        '--password',
        required=True,
        help='The secret developer password required to run the cleanup.'
    )
    
    print("*"*60)
    print("WARNING: This is a developer-only tool.")
    print("Running this will permanently delete all trial data.")
    print("*"*60)

    try:
        args = parser.parse_args()
        if args.password.strip() == DEV_PASSWORD:
            print("\nDeveloper password accepted.")
            clean_all_artifacts()
        else:
            print("\n[ACCESS DENIED] Incorrect developer password.")
            sys.exit(1)
    except SystemExit as e:
        if e.code != 0:
             print("\nTo use this script, you must provide the correct password.")
             print(f"Example: python {sys.argv[0]} --password={DEV_PASSWORD}")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
